[package]
name = "rustimage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
num-complex = "0.4.3"
clap = {version="4.0.32", features=["derive"]}
rand = "0.8.5"