service: random-fact-generator

provider:
  name: aws
  runtime: provided.al2

package:
  exclude:
    - ./**
  include:
    - ./bootstrap

functions:
  rand-fact-generator-rust:
    handler: ./bootstrap
    events:
      - http:
          path: /fact
          method: GET